import React, { useState, useCallback, memo } from 'react';
import {
  View,
  Text,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  TouchableOpacity,
  Alert,
  StyleSheet,
  Modal,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Mail, Lock, User, Leaf, X, ChevronRight } from 'lucide-react-native';
import { Input } from '../../components/ui/Input';
import { Button } from '../../components/ui/Button';
import { useAppStore } from '../../store/useAppStore';
import { authService } from '../../services/supabase';
import { useTranslation } from '../../hooks/useTranslation';

// ─── Policy content ───────────────────────────────────────────────
const PRIVACY_POLICY = `PRIVACY POLICY
Last updated: January 1, 2025

1. INFORMATION WE COLLECT
Farmora collects information you provide directly, such as your name, email address, and farm-related data (crop types, location, soil conditions). We also collect device information and usage analytics to improve the app experience.

2. HOW WE USE YOUR INFORMATION
We use your information to:
• Provide personalised crop recommendations and market prices
• Send weather alerts and farming reminders
• Improve our AI disease detection models
• Communicate important updates about the service

3. DATA SHARING
We do not sell your personal data. We share data only with:
• Service providers (e.g., Supabase for database hosting)
• Analytics partners to improve app performance
• Government bodies when required by law

4. DATA SECURITY
We implement industry-standard encryption (TLS 1.3) for data in transit and AES-256 encryption for data at rest. Access to your data is restricted to authorised personnel only.

5. YOUR RIGHTS
You have the right to access, correct, or delete your personal data at any time. Contact us at privacy@farmora.in to exercise these rights.

6. DATA RETENTION
We retain your data for as long as your account is active, or as required by law. You may delete your account and all associated data at any time from the Profile settings.

7. COOKIES & ANALYTICS
We use anonymised analytics to understand how the app is used. No personally identifiable information is shared with third-party analytics providers.

8. CHANGES TO THIS POLICY
We will notify you of significant changes to this policy via in-app notifications and email.

9. CONTACT US
Farmora Technologies Pvt. Ltd.
Email: privacy@farmora.in
Address: Hyderabad, Telangana, India`;

const TERMS_OF_SERVICE = `TERMS OF SERVICE
Last updated: January 1, 2025

1. ACCEPTANCE OF TERMS
By creating a Farmora account and using the application, you agree to be bound by these Terms of Service. If you do not agree, please do not use the app.

2. ELIGIBILITY
You must be at least 18 years old to use Farmora. By using the app, you represent that you meet this requirement.

3. YOUR ACCOUNT
You are responsible for maintaining the security of your account credentials. Farmora is not liable for any losses resulting from unauthorised access due to your failure to keep credentials secure.

4. PERMITTED USE
Farmora is designed exclusively for agricultural planning, crop monitoring, and market price discovery. You agree not to misuse the platform for any unlawful or unauthorised purpose.

5. AI RECOMMENDATIONS DISCLAIMER
Crop recommendations, disease diagnoses, and market insights provided by Farmora are generated by AI models and are intended as guidance only. Always consult a qualified agronomist before making major farming decisions. Farmora is not liable for losses arising from reliance on AI-generated advice.

6. INTELLECTUAL PROPERTY
All content, features, and functionality in the Farmora app are the exclusive property of Farmora Technologies Pvt. Ltd. and are protected by intellectual property laws.

7. USER-GENERATED CONTENT
By uploading photos or data to Farmora, you grant us a non-exclusive, royalty-free licence to use that content solely to provide and improve our services.

8. SERVICE AVAILABILITY
We aim for 99.5% uptime but do not guarantee uninterrupted access. Scheduled maintenance will be communicated in advance wherever possible.

9. LIMITATION OF LIABILITY
To the maximum extent permitted by law, Farmora shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.

10. TERMINATION
Farmora reserves the right to suspend or terminate your account if you violate these terms, without prior notice.

11. GOVERNING LAW
These Terms are governed by the laws of India. Disputes shall be resolved in the courts of Hyderabad, Telangana.

12. CONTACT US
Farmora Technologies Pvt. Ltd.
Email: legal@farmora.in
Address: Hyderabad, Telangana, India`;

// ─── Reusable Policy Modal ────────────────────────────────────────
function PolicyModal({
  visible,
  title,
  content,
  onClose,
}: {
  visible: boolean;
  title: string;
  content: string;
  onClose: () => void;
}) {
  return (
    <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}>
      <View style={m.overlay}>
        <SafeAreaView style={m.sheet}>
          <View style={m.sheetHeader}>
            <Text style={m.sheetTitle}>{title}</Text>
            <TouchableOpacity onPress={onClose} style={m.closeBtn} hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}>
              <X size={20} color="#006e2f" />
            </TouchableOpacity>
          </View>
          <ScrollView style={m.sheetBody} showsVerticalScrollIndicator={false}>
            <Text style={m.sheetContent}>{content}</Text>
            <View style={{ height: 32 }} />
          </ScrollView>
          <View style={m.sheetFooter}>
            <TouchableOpacity style={m.doneBtn} onPress={onClose} activeOpacity={0.85}>
              <Text style={m.doneBtnText}>I've Read This</Text>
              <ChevronRight size={16} color="#fff" />
            </TouchableOpacity>
          </View>
        </SafeAreaView>
      </View>
    </Modal>
  );
}

// ─── Signup Screen ────────────────────────────────────────────────
function SignupScreen() {
  const router = useRouter();
  const setUser = useAppStore((s) => s.setUser);
  const setProfile = useAppStore((s) => s.setProfile);
  const language = useAppStore((s) => s.language);
  const { t } = useTranslation();

  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [agreeToTerms, setAgreeToTerms] = useState(false);
  const [showPrivacy, setShowPrivacy] = useState(false);
  const [showTerms, setShowTerms] = useState(false);

  const validate = () => {
    const newErrors: Record<string, string> = {};
    if (!fullName) newErrors.fullName = 'Full Name is required';
    if (!email) newErrors.email = 'Email is required';
    else if (!/\S+@\S+\.\S+/.test(email)) newErrors.email = 'Invalid email address';
    if (!password) newErrors.password = 'Password is required';
    else if (password.length < 6) newErrors.password = 'Password must be at least 6 characters';
    if (password !== confirmPassword) newErrors.confirmPassword = 'Passwords do not match';
    if (!agreeToTerms) {
      Alert.alert(
        'Agreement Required',
        'You must read and agree to the Privacy Policy and Terms of Service to continue.'
      );
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0 && agreeToTerms;
  };

  const handleSignup = async () => {
    if (!validate()) return;
    setLoading(true);
    try {
      const data = await authService.signUp(email, password, fullName, language);
      if (data.user) {
        await setUser(data.user);
        const profile = { id: data.user.id, full_name: fullName, language };
        await setProfile(profile);
        router.replace('/(auth)/location');
      }
    } catch (e: any) {
      Alert.alert('Signup error', e.message ?? 'Unexpected error');
    } finally {
      setLoading(false);
    }
  };

  const onFullNameChange = useCallback((text: string) => setFullName(text), []);
  const onEmailChange = useCallback((text: string) => setEmail(text), []);
  const onPasswordChange = useCallback((text: string) => setPassword(text), []);
  const onConfirmPasswordChange = useCallback((text: string) => setConfirmPassword(text), []);

  return (
    <>
      <PolicyModal
        visible={showPrivacy}
        title="Privacy Policy"
        content={PRIVACY_POLICY}
        onClose={() => setShowPrivacy(false)}
      />
      <PolicyModal
        visible={showTerms}
        title="Terms of Service"
        content={TERMS_OF_SERVICE}
        onClose={() => setShowTerms(false)}
      />

      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        style={[s.flex1, { backgroundColor: '#f3fcef' }]}
      >
        <View style={s.flex1}>
          <ScrollView
            contentContainerStyle={s.scrollContent}
            style={s.scrollView}
            showsVerticalScrollIndicator={false}
            keyboardShouldPersistTaps="always"
          >
            <View style={s.logoContainer}>
              <View style={s.logoRow}>
                <View style={s.logoIcon}>
                  <Leaf size={20} color="white" fill="white" />
                </View>
                <Text style={s.logoText}>Farmora</Text>
              </View>
              <Text style={s.subtitle}>Empowering sustainable agriculture through intelligence.</Text>
            </View>

            <View style={s.formCard}>
              <View style={s.tabContainer}>
                <TouchableOpacity
                  onPress={() => router.replace('/(auth)/login')}
                  style={s.inactiveTab}
                >
                  <Text style={s.inactiveTabText}>{t('login')}</Text>
                </TouchableOpacity>
                <TouchableOpacity style={s.activeTab}>
                  <Text style={s.activeTabText}>{t('signup')}</Text>
                </TouchableOpacity>
              </View>

              <Text style={s.titleText}>{t('create_account')}</Text>
              <Text style={s.descriptionText}>{t('join_farmora')}</Text>

              <Input
                label="Full Name"
                placeholder="Rajesh Kumar"
                value={fullName}
                onChangeText={onFullNameChange}
                error={errors.fullName}
                icon={User}
              />
              <Input
                label={t('email_label')}
                placeholder={t('email_placeholder')}
                value={email}
                onChangeText={onEmailChange}
                error={errors.email}
                icon={Mail}
                keyboardType="email-address"
                autoCapitalize="none"
              />
              <Input
                label={t('password_label')}
                placeholder={t('password_placeholder')}
                value={password}
                onChangeText={onPasswordChange}
                error={errors.password}
                icon={Lock}
                secureTextEntry
              />
              <Input
                label="Confirm Password"
                placeholder={t('password_placeholder')}
                value={confirmPassword}
                onChangeText={onConfirmPasswordChange}
                error={errors.confirmPassword}
                icon={Lock}
                secureTextEntry
              />

              {/* ─── Terms Checkbox ─────────────────────────────── */}
              <TouchableOpacity
                onPress={() => setAgreeToTerms(!agreeToTerms)}
                style={s.checkboxRow}
                activeOpacity={0.7}
              >
                <View style={[s.checkboxBox, agreeToTerms ? s.checkboxChecked : s.checkboxUnchecked]}>
                  {agreeToTerms && <View style={s.checkboxInner} />}
                </View>
                <Text style={s.checkboxLabel}>
                  I have read and agree to the{' '}
                  <Text
                    style={s.linkText}
                    onPress={() => setShowPrivacy(true)}
                  >
                    Privacy Policy
                  </Text>
                  {' '}and{' '}
                  <Text
                    style={s.linkText}
                    onPress={() => setShowTerms(true)}
                  >
                    Terms of Service
                  </Text>
                </Text>
              </TouchableOpacity>

              <Button
                title={t('continue_btn')}
                onPress={handleSignup}
                loading={loading}
                variant="primary"
                showArrow
                style={{ width: '100%', height: 52 }}
              />
            </View>

            <View style={s.footer}>
              <View style={s.footerLinks}>
                <TouchableOpacity onPress={() => setShowPrivacy(true)}>
                  <Text style={s.footerLinkText}>Privacy Policy</Text>
                </TouchableOpacity>
                <Text style={{ color: '#bccbb9' }}>•</Text>
                <TouchableOpacity onPress={() => setShowTerms(true)}>
                  <Text style={s.footerLinkText}>Terms of Service</Text>
                </TouchableOpacity>
              </View>
              <Text style={s.copyrightText}>© 2024 Farmora Technologies. All rights reserved.</Text>
            </View>
          </ScrollView>
        </View>
      </KeyboardAvoidingView>
    </>
  );
}

// ─── Styles ───────────────────────────────────────────────────────
const s = StyleSheet.create({
  flex1: { flex: 1 },
  scrollView: { paddingHorizontal: 24, paddingVertical: 24 },
  scrollContent: { flexGrow: 1, justifyContent: 'center' },
  logoContainer: { alignItems: 'center', marginBottom: 24, marginTop: 16 },
  logoRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 8 },
  logoIcon: { width: 40, height: 40, backgroundColor: '#006e2f', borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  logoText: { fontSize: 24, fontWeight: '700', color: '#006e2f' },
  subtitle: { fontSize: 13, fontWeight: '500', color: '#6d7b6c', textAlign: 'center' },
  formCard: { backgroundColor: '#ffffff', padding: 24, marginBottom: 24, borderRadius: 36, shadowColor: '#166534', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.06, shadowRadius: 20, elevation: 4, borderWidth: 1, borderColor: '#edf6ea' },
  tabContainer: { backgroundColor: '#edf6ea', borderRadius: 9999, padding: 4, flexDirection: 'row', marginBottom: 24 },
  activeTab: { flex: 1, paddingVertical: 12, alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 9999, shadowColor: '#166534', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 },
  activeTabText: { fontWeight: '700', fontSize: 14, color: '#006e2f' },
  inactiveTab: { flex: 1, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  inactiveTabText: { fontWeight: '600', fontSize: 14, color: '#6d7b6c' },
  titleText: { fontSize: 22, fontWeight: '700', color: '#161d16', marginBottom: 4 },
  descriptionText: { fontSize: 13, fontWeight: '400', color: '#6d7b6c', marginBottom: 24, lineHeight: 20 },
  checkboxRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 24, marginTop: 8 },
  checkboxBox: { width: 20, height: 20, borderRadius: 6, borderWidth: 1.5, marginRight: 10, alignItems: 'center', justifyContent: 'center', marginTop: 2, flexShrink: 0 },
  checkboxChecked: { backgroundColor: '#059669', borderColor: '#059669' },
  checkboxUnchecked: { borderColor: '#94a3b8', backgroundColor: '#ffffff' },
  checkboxInner: { width: 10, height: 10, backgroundColor: '#ffffff', borderRadius: 2 },
  checkboxLabel: { fontSize: 13, color: '#6d7b6c', flex: 1, lineHeight: 20 },
  linkText: { fontWeight: '700', color: '#006e2f', textDecorationLine: 'underline' },
  footer: { alignItems: 'center', marginTop: 8, marginBottom: 16 },
  footerLinks: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, marginBottom: 8 },
  footerLinkText: { fontSize: 12, fontWeight: '700', color: '#006e2f', textDecorationLine: 'underline' },
  copyrightText: { fontSize: 12, fontWeight: '500', color: '#bccbb9', textAlign: 'center' },
});

// ─── Modal Styles ─────────────────────────────────────────────────
const m = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  sheet: { backgroundColor: '#ffffff', borderTopLeftRadius: 28, borderTopRightRadius: 28, maxHeight: '88%', minHeight: '55%', shadowColor: '#000', shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.15, shadowRadius: 16, elevation: 24 },
  sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 24, paddingTop: 20, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#edf6ea' },
  sheetTitle: { fontSize: 18, fontWeight: '800', color: '#006e2f' },
  closeBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#edf6ea', alignItems: 'center', justifyContent: 'center' },
  sheetBody: { flex: 1, paddingHorizontal: 24, paddingTop: 16 },
  sheetContent: { fontSize: 13.5, lineHeight: 22, color: '#374151', fontWeight: '400' },
  sheetFooter: { paddingHorizontal: 24, paddingVertical: 16, borderTopWidth: 1, borderTopColor: '#edf6ea' },
  doneBtn: { backgroundColor: '#006e2f', borderRadius: 14, paddingVertical: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  doneBtnText: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
});

export default memo(SignupScreen);
