import { StyleSheet, Platform } from 'react-native';

export const calendarColors = {
  primary: '#2E7D32',
  primaryLight: '#E8F5E9',
  background: '#F5F7F4',
  card: '#FFFFFF',
  textDark: '#1B5E20',
  textGray: '#556F57',
  textBlack: '#212121',
  border: '#E2E8F0',
  white: '#FFFFFF',
  warning: '#F9A825',
  warningBg: '#FFFDE7',
  shadowColor: '#000000',
};

export const calendarStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: calendarColors.background,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: calendarColors.white,
    borderBottomWidth: 1,
    borderBottomColor: '#EAF0EB',
  },
  headerGreeting: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '800',
    color: calendarColors.textGray,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  headerTitle: {
    fontFamily: 'Inter',
    fontSize: 26,
    fontWeight: '900',
    color: calendarColors.textDark,
  },
  headerSubtitle: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '600',
    color: '#667C69',
    marginTop: 2,
  },
  // Horizontal Calendar Strip
  stripScroll: {
    backgroundColor: calendarColors.white,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EAF0EB',
  },
  stripContent: {
    paddingHorizontal: 8,
    gap: 8,
    flexDirection: 'row',
  },
  dateCard: {
    width: 60,
    height: 76,
    borderRadius: 18,
    backgroundColor: '#FAFCFA',
    borderWidth: 1.5,
    borderColor: '#E1EBE2',
    justifyContent: 'center',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: calendarColors.shadowColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
      },
      android: {
        elevation: 1,
      },
    }),
  },
  dateCardToday: {
    borderColor: calendarColors.primary,
  },
  dateCardSelected: {
    backgroundColor: calendarColors.primary,
    borderColor: calendarColors.primary,
    ...Platform.select({
      ios: {
        shadowColor: calendarColors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  dayName: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '800',
    color: calendarColors.textGray,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  dayNameSelected: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  dayNumber: {
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '900',
    color: calendarColors.textBlack,
  },
  dayNumberSelected: {
    color: calendarColors.white,
  },
  todayIndicator: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: calendarColors.primary,
    position: 'absolute',
    bottom: 6,
  },
  todayIndicatorSelected: {
    backgroundColor: calendarColors.white,
  },
  // Content Sections
  mainScroll: {
    flex: 1,
  },
  mainScrollContent: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 100, // Safe space for floating button
  },
  sectionTitle: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '900',
    color: calendarColors.textDark,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  // Task Card styling
  taskCardContainer: {
    flexDirection: 'row',
    marginBottom: 14,
    alignItems: 'stretch',
  },
  timeCol: {
    width: 70,
    paddingRight: 10,
    paddingTop: 12,
    alignItems: 'flex-end',
  },
  timeText: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '800',
    color: calendarColors.textGray,
  },
  cardMain: {
    flex: 1,
    backgroundColor: calendarColors.card,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8EFE9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...Platform.select({
      ios: {
        shadowColor: calendarColors.shadowColor,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.04,
        shadowRadius: 6,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  cardCompleted: {
    backgroundColor: '#FAFCFA',
    borderColor: '#E0E8E1',
    opacity: 0.75,
  },
  cardLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  badge: {
    width: 42,
    height: 42,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailsBlock: {
    flex: 1,
  },
  taskHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  categoryLabel: {
    fontFamily: 'Inter',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  taskTitle: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '900',
    color: calendarColors.textBlack,
    marginTop: 2,
  },
  taskTitleCompleted: {
    textDecorationLine: 'line-through',
    color: '#888888',
  },
  taskNotes: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '500',
    color: '#666666',
    marginTop: 4,
    lineHeight: 18,
  },
  checkboxWrapper: {
    marginLeft: 12,
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#94A3B8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    borderColor: calendarColors.primary,
    backgroundColor: calendarColors.primary,
  },
  // Empty State
  emptyCard: {
    backgroundColor: calendarColors.card,
    borderRadius: 24,
    padding: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#C8DCD0',
    marginVertical: 10,
  },
  emptyEmoji: {
    fontSize: 36,
    marginBottom: 12,
  },
  emptyText: {
    fontFamily: 'Inter',
    fontSize: 15,
    fontWeight: '700',
    color: calendarColors.textGray,
    textAlign: 'center',
    lineHeight: 22,
  },
  // Weather Advisor Card
  weatherCard: {
    backgroundColor: calendarColors.warningBg,
    borderRadius: 20,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#FBE9E7',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  weatherInfo: {
    flex: 1,
  },
  weatherTitle: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '900',
    color: '#D84315',
  },
  weatherDesc: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '700',
    color: '#E64A19',
    marginTop: 2,
  },
  // Upcoming list
  upcomingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: calendarColors.card,
    padding: 14,
    borderRadius: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#EAF0EB',
  },
  upcomingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 12,
  },
  upcomingText: {
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '800',
    color: calendarColors.textBlack,
  },
  upcomingDateText: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '800',
    color: calendarColors.textGray,
    backgroundColor: '#E8F1EA',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  // Add Task Floating Button
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 20,
    backgroundColor: calendarColors.primary,
    height: 52,
    borderRadius: 26,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    ...Platform.select({
      ios: {
        shadowColor: calendarColors.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  fabText: {
    fontFamily: 'Inter',
    fontSize: 15,
    fontWeight: '800',
    color: calendarColors.white,
    marginLeft: 6,
    letterSpacing: 0.5,
  },
  // Modal / Bottom Sheet Form
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: calendarColors.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: Platform.OS === 'ios' ? 44 : 24,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '900',
    color: calendarColors.textDark,
  },
  modalCloseBtn: {
    padding: 4,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '800',
    color: calendarColors.textGray,
    textTransform: 'uppercase',
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  textInput: {
    height: 48,
    borderWidth: 1.5,
    borderColor: calendarColors.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    fontFamily: 'Inter',
    fontSize: 15,
    color: calendarColors.textBlack,
    backgroundColor: '#FAFCFA',
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
    paddingTop: 12,
  },
  typeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
    marginBottom: 8,
  },
  typeTag: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: calendarColors.border,
    backgroundColor: '#FAFCFA',
    gap: 6,
  },
  typeTagSelected: {
    borderColor: calendarColors.primary,
    backgroundColor: calendarColors.primaryLight,
  },
  typeEmoji: {
    fontSize: 15,
  },
  typeTagText: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '800',
    color: calendarColors.textGray,
  },
  typeTagTextSelected: {
    color: calendarColors.primary,
  },
  submitBtn: {
    backgroundColor: calendarColors.primary,
    height: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  submitBtnText: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '900',
    color: calendarColors.white,
    letterSpacing: 0.5,
  },
});
