import { StyleSheet, Platform } from 'react-native';

export const marketColors = {
  primary: '#2E7D32',
  primaryLight: '#E8F5E9',
  background: '#F5F7F4',
  card: '#FFFFFF',
  textDark: '#1B5E20',
  textGray: '#757575',
  border: '#E0E0E0',
  placeholder: '#9E9E9E',
  shadow: '#000000',
  error: '#D32F2F',
};

export const marketStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: marketColors.background,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  headerCard: {
    backgroundColor: marketColors.card,
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E8F0E5',
    ...Platform.select({
      ios: {
        shadowColor: marketColors.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  headerTitle: {
    fontFamily: 'Inter',
    fontSize: 24,
    fontWeight: '900',
    color: marketColors.textDark,
    marginBottom: 8,
  },
  headerSubtitle: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '600',
    color: marketColors.textGray,
    lineHeight: 20,
  },
  formCard: {
    backgroundColor: marketColors.card,
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E8F0E5',
    ...Platform.select({
      ios: {
        shadowColor: marketColors.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  fieldGroup: {
    marginBottom: 18,
  },
  fieldLabel: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '800',
    color: marketColors.textDark,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dropdownContainer: {
    height: 56,
    borderColor: marketColors.border,
    borderWidth: 1.5,
    borderRadius: 16,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
  },
  dropdownActive: {
    borderColor: marketColors.primary,
  },
  dropdownDisabled: {
    backgroundColor: '#FAFAFA',
    borderColor: '#EEEEEE',
  },
  dropdownText: {
    fontFamily: 'Inter',
    fontSize: 16,
    color: '#333333',
  },
  dropdownPlaceholder: {
    fontFamily: 'Inter',
    fontSize: 15,
    color: marketColors.placeholder,
  },
  dropdownSearchInput: {
    height: 48,
    fontFamily: 'Inter',
    fontSize: 15,
    borderRadius: 12,
    borderColor: marketColors.border,
    color: '#333333',
  },
  cropGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  cropTag: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: marketColors.border,
    backgroundColor: '#FFFFFF',
    minWidth: '22%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cropTagSelected: {
    borderColor: marketColors.primary,
    backgroundColor: marketColors.primaryLight,
  },
  cropTagText: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '700',
    color: marketColors.textGray,
  },
  cropTagTextSelected: {
    color: marketColors.primary,
  },
  btnPrimary: {
    backgroundColor: marketColors.primary,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 10,
    ...Platform.select({
      ios: {
        shadowColor: marketColors.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  btnPrimaryDisabled: {
    backgroundColor: '#BDBDBD',
    shadowOpacity: 0,
    elevation: 0,
  },
  btnPrimaryText: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  btnIcon: {
    marginRight: 8,
  },
  // Toggle Row Styles
  toggleRow: {
    flexDirection: 'row',
    backgroundColor: '#E8ECE6',
    borderRadius: 16,
    padding: 4,
    marginBottom: 16,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 12,
  },
  toggleBtnActive: {
    backgroundColor: '#2E7D32',
  },
  toggleBtnText: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '700',
    color: '#666666',
  },
  toggleBtnTextActive: {
    color: '#FFFFFF',
  },
  // Collapsed Filter Bar
  collapsedFilterCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 18,
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8F0E5',
    ...Platform.select({
      ios: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 6,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  collapsedFilterTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  collapsedFilterText: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '700',
    color: '#1B5E20',
    marginLeft: 6,
  },
  editFiltersText: {
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: '800',
    color: '#2E7D32',
  },
  // Card styles
  listingCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E8F0E5',
    ...Platform.select({
      ios: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 10,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardAvatar: {
    width: 44,
    height: 44,
    borderRadius: 16,
    marginRight: 12,
  },
  cardHeaderText: {
    flex: 1,
  },
  cardName: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '800',
    color: '#1B5E20',
    marginBottom: 2,
  },
  cardRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardRatingText: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '700',
    color: '#555555',
    marginLeft: 4,
  },
  badgeRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  roleBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  roleBadgeSeller: {
    backgroundColor: '#E8F5E9',
  },
  roleBadgeBuyer: {
    backgroundColor: '#E0F2FE',
  },
  roleBadgeTextSeller: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '800',
    color: '#2E7D32',
    textTransform: 'uppercase',
  },
  roleBadgeTextBuyer: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '800',
    color: '#0369A1',
    textTransform: 'uppercase',
  },
  cropBadge: {
    backgroundColor: '#F1F5F0',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  cropBadgeText: {
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: '800',
    color: '#496A44',
  },
  cardDetails: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F1F5F0',
    paddingVertical: 12,
    marginBottom: 12,
  },
  cardDetailCol: {
    flex: 1,
  },
  cardDetailLabel: {
    fontFamily: 'Inter',
    fontSize: 10,
    fontWeight: '700',
    color: '#999999',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  cardDetailValue: {
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '900',
    color: '#1B5E20',
  },
  cardLocationText: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '600',
    color: '#757575',
    marginLeft: 4,
    flex: 1,
  },
  cardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  cardLocationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 10,
  },
  cardActions: {
    flexDirection: 'row',
    gap: 8,
  },
  actionBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
  },
  actionBtnCall: {
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  actionBtnWhatsapp: {
    borderColor: '#DCFCE7',
    backgroundColor: '#DCFCE7',
  },
  actionBtnMaps: {
    borderColor: '#E0F2FE',
    backgroundColor: '#E0F2FE',
  },
  // Empty state
  emptyContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E8F0E5',
    marginTop: 10,
    ...Platform.select({
      ios: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 10,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  emptyIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 24,
    backgroundColor: '#F1F5F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '800',
    color: '#1B5E20',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontFamily: 'Inter',
    fontSize: 14,
    color: '#757575',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  emptyBtn: {
    backgroundColor: '#2E7D32',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 14,
  },
  emptyBtnText: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  // Modal overlay
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    width: '100%',
    maxHeight: '90%',
    borderRadius: 28,
    padding: 24,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontFamily: 'Inter',
    fontSize: 20,
    fontWeight: '900',
    color: '#1B5E20',
  },
  modalCloseBtn: {
    padding: 4,
  },
  modalScroll: {
    marginBottom: 20,
  },
  modalSectionTitle: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '800',
    color: '#1B5E20',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 10,
    marginTop: 8,
  },
  textInput: {
    height: 56,
    borderWidth: 1.5,
    borderColor: '#E0E0E0',
    borderRadius: 16,
    paddingHorizontal: 16,
    fontFamily: 'Inter',
    fontSize: 16,
    color: '#333333',
    backgroundColor: '#FFFFFF',
  },
  textInputActive: {
    borderColor: '#2E7D32',
  },
  roleSelectGroup: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
  },
  roleSelectBtn: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  roleSelectBtnActiveSeller: {
    borderColor: '#2E7D32',
    backgroundColor: '#E8F5E9',
  },
  roleSelectBtnActiveBuyer: {
    borderColor: '#0284C7',
    backgroundColor: '#E0F2FE',
  },
  roleSelectBtnText: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '800',
    color: '#64748B',
  },
  roleSelectBtnTextActiveSeller: {
    color: '#2E7D32',
  },
  roleSelectBtnTextActiveBuyer: {
    color: '#0284C7',
  },
  modalBtnRow: {
    flexDirection: 'row',
    gap: 12,
  },
  modalBtnCancel: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBtnCancelText: {
    fontFamily: 'Inter',
    fontSize: 15,
    fontWeight: '800',
    color: '#64748B',
  },
  modalBtnSubmit: {
    flex: 2,
    height: 52,
    borderRadius: 16,
    backgroundColor: '#2E7D32',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBtnSubmitText: {
    fontFamily: 'Inter',
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});

