import React from 'react';
import { View, Text, ScrollView, TouchableOpacity } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ArrowLeft, BookOpen, ShieldAlert } from 'lucide-react-native';
import { FarmoraColors } from '../constants/colors';

export default function TermsScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();

  return (
    <View className="flex-1 bg-slate-50" style={{ paddingTop: insets.top }}>
      {/* Header */}
      <View className="flex-row items-center justify-between px-5 py-4 bg-white border-b border-slate-100">
        <TouchableOpacity 
          onPress={() => router.back()} 
          className="w-10 h-10 rounded-full bg-slate-100 items-center justify-center active:scale-95"
        >
          <ArrowLeft size={18} color="#1E293B" />
        </TouchableOpacity>
        <Text style={{ fontFamily: 'Inter', fontSize: 16, fontWeight: '800', color: '#1E293B' }}>
          Terms & Privacy
        </Text>
        <View className="w-10" />
      </View>

      <ScrollView 
        className="flex-1 px-5 pt-5" 
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{ paddingBottom: 60 }}
      >
        <View className="bg-white rounded-3xl p-5 border border-slate-100 shadow-sm mb-6">
          <View className="flex-row items-center gap-2 mb-4">
            <BookOpen size={18} color={FarmoraColors.primary} />
            <Text style={{ fontFamily: 'Inter', fontSize: 14, fontWeight: '800', color: '#0F172A' }}>
              Terms of Service
            </Text>
          </View>
          
          <Text style={{ fontFamily: 'Inter', fontSize: 11, fontWeight: '600', color: '#64748B' }} className="mb-4">
            Last Updated: May 2026
          </Text>

          <Text style={{ fontFamily: 'Inter', fontSize: 13, fontWeight: '800', color: '#1E293B' }} className="mb-1.5">
            1. Acceptance of Terms
          </Text>
          <Text style={{ fontFamily: 'Inter', fontSize: 12, color: '#475569', lineHeight: 18 }} className="mb-4">
            By downloading, installing, or using the Farmora application, you agree to comply with and be bound by these Terms of Service. If you do not agree, please do not access or use the application.
          </Text>

          <Text style={{ fontFamily: 'Inter', fontSize: 13, fontWeight: '800', color: '#1E293B' }} className="mb-1.5">
            2. Account Registration & Verifications
          </Text>
          <Text style={{ fontFamily: 'Inter', fontSize: 12, color: '#475569', lineHeight: 18 }} className="mb-4">
            To unlock certain features such as listing organic grains in the Farmora local markets, you must register a profile. You agree to provide accurate information and verify your contact details. Farmora is not responsible for verified user transaction disputes.
          </Text>

          <Text style={{ fontFamily: 'Inter', fontSize: 13, fontWeight: '800', color: '#1E293B' }} className="mb-1.5">
            3. Crop Scans & Medical Advice Disclaimer
          </Text>
          <Text style={{ fontFamily: 'Inter', fontSize: 12, color: '#475569', lineHeight: 18 }} className="mb-4">
            Crop diagnostics, pest alerts, and disease assessments are generated by machine learning models. These recommendations should not replace professional agricultural consultancy services. Farmora does not guarantee crop health outcomes based solely on diagnostic outputs.
          </Text>

          <Text style={{ fontFamily: 'Inter', fontSize: 13, fontWeight: '800', color: '#1E293B' }} className="mb-1.5">
            4. Geographic Location Services
          </Text>
          <Text style={{ fontFamily: 'Inter', fontSize: 12, color: '#475569', lineHeight: 18 }} className="mb-4">
            We collect location coordinates to retrieve accurate weather forecasts, calculate distances to nearby grain sellers, and map pest outbreak distributions. You can turn off GPS permissions anytime, but some localized views will become unavailable.
          </Text>
        </View>

        <View className="bg-white rounded-3xl p-5 border border-slate-100 shadow-sm mb-6">
          <View className="flex-row items-center gap-2 mb-3">
            <ShieldAlert size={18} color="#EA580C" />
            <Text style={{ fontFamily: 'Inter', fontSize: 14, fontWeight: '800', color: '#0F172A' }}>
              Privacy Statement
            </Text>
          </View>
          <Text style={{ fontFamily: 'Inter', fontSize: 12, color: '#475569', lineHeight: 18 }}>
            Farmora respects your privacy. We do not sell your personal profile data or exact farm locations to third-party entities. Accumulated disease outbreaks and product price indices are aggregated and anonymized for analytics to improve local harvest yields.
          </Text>
        </View>

        {/* Dismiss Button */}
        <TouchableOpacity
          onPress={() => router.back()}
          className="bg-emerald-600 py-3.5 rounded-2xl items-center justify-center active:scale-[0.98] mb-8"
        >
          <Text style={{ fontFamily: 'Inter', fontSize: 13, fontWeight: '800', color: '#FFFFFF' }}>
            I Understand & Agree
          </Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
}
